version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: hengich/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/app/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: hengich/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  nginx:
    env_file: .env
    image: hengich/foodgram_gateway
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - frontend
      - backend